// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/adapters/grpc/proto/dws_message_fwd.proto

package dws_message_fwd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichedEventPayloadMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // For arbitrary JSON-like data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedEventPayloadMessage) Reset() {
	*x = EnrichedEventPayloadMessage{}
	mi := &file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedEventPayloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedEventPayloadMessage) ProtoMessage() {}

func (x *EnrichedEventPayloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedEventPayloadMessage.ProtoReflect.Descriptor instead.
func (*EnrichedEventPayloadMessage) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichedEventPayloadMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EnrichedEventPayloadMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushEventRequest struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Payload         *EnrichedEventPayloadMessage `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	TargetCompanyId string                       `protobuf:"bytes,2,opt,name=target_company_id,json=targetCompanyId,proto3" json:"target_company_id,omitempty"` // For routing/logging on recipient
	TargetAgentId   string                       `protobuf:"bytes,3,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	TargetChatId    string                       `protobuf:"bytes,4,opt,name=target_chat_id,json=targetChatId,proto3" json:"target_chat_id,omitempty"`
	SourcePodId     string                       `protobuf:"bytes,5,opt,name=source_pod_id,json=sourcePodId,proto3" json:"source_pod_id,omitempty"` // Added to track source for metrics
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushEventRequest) Reset() {
	*x = PushEventRequest{}
	mi := &file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventRequest) ProtoMessage() {}

func (x *PushEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventRequest.ProtoReflect.Descriptor instead.
func (*PushEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescGZIP(), []int{1}
}

func (x *PushEventRequest) GetPayload() *EnrichedEventPayloadMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushEventRequest) GetTargetCompanyId() string {
	if x != nil {
		return x.TargetCompanyId
	}
	return ""
}

func (x *PushEventRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *PushEventRequest) GetTargetChatId() string {
	if x != nil {
		return x.TargetChatId
	}
	return ""
}

func (x *PushEventRequest) GetSourcePodId() string {
	if x != nil {
		return x.SourcePodId
	}
	return ""
}

type PushEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional: error message or status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEventResponse) Reset() {
	*x = PushEventResponse{}
	mi := &file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventResponse) ProtoMessage() {}

func (x *PushEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventResponse.ProtoReflect.Descriptor instead.
func (*PushEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescGZIP(), []int{2}
}

func (x *PushEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_adapters_grpc_proto_dws_message_fwd_proto protoreflect.FileDescriptor

const file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDesc = "" +
	"\n" +
	"2internal/adapters/grpc/proto/dws_message_fwd.proto\x12\x0fdws_message_fwd\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd6\x01\n" +
	"\x1bEnrichedEventPayloadMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xf8\x01\n" +
	"\x10PushEventRequest\x12F\n" +
	"\apayload\x18\x01 \x01(\v2,.dws_message_fwd.EnrichedEventPayloadMessageR\apayload\x12*\n" +
	"\x11target_company_id\x18\x02 \x01(\tR\x0ftargetCompanyId\x12&\n" +
	"\x0ftarget_agent_id\x18\x03 \x01(\tR\rtargetAgentId\x12$\n" +
	"\x0etarget_chat_id\x18\x04 \x01(\tR\ftargetChatId\x12\"\n" +
	"\rsource_pod_id\x18\x05 \x01(\tR\vsourcePodId\"G\n" +
	"\x11PushEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2n\n" +
	"\x18MessageForwardingService\x12R\n" +
	"\tPushEvent\x12!.dws_message_fwd.PushEventRequest\x1a\".dws_message_fwd.PushEventResponseBVZTgitlab.com/timkado/api/daisi-ws-service/internal/adapters/grpc/proto;dws_message_fwdb\x06proto3"

var (
	file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescOnce sync.Once
	file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescData []byte
)

func file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescGZIP() []byte {
	file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescOnce.Do(func() {
		file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDesc), len(file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDesc)))
	})
	return file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDescData
}

var file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_adapters_grpc_proto_dws_message_fwd_proto_goTypes = []any{
	(*EnrichedEventPayloadMessage)(nil), // 0: dws_message_fwd.EnrichedEventPayloadMessage
	(*PushEventRequest)(nil),            // 1: dws_message_fwd.PushEventRequest
	(*PushEventResponse)(nil),           // 2: dws_message_fwd.PushEventResponse
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),             // 4: google.protobuf.Struct
}
var file_internal_adapters_grpc_proto_dws_message_fwd_proto_depIdxs = []int32{
	3, // 0: dws_message_fwd.EnrichedEventPayloadMessage.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: dws_message_fwd.EnrichedEventPayloadMessage.data:type_name -> google.protobuf.Struct
	0, // 2: dws_message_fwd.PushEventRequest.payload:type_name -> dws_message_fwd.EnrichedEventPayloadMessage
	1, // 3: dws_message_fwd.MessageForwardingService.PushEvent:input_type -> dws_message_fwd.PushEventRequest
	2, // 4: dws_message_fwd.MessageForwardingService.PushEvent:output_type -> dws_message_fwd.PushEventResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_adapters_grpc_proto_dws_message_fwd_proto_init() }
func file_internal_adapters_grpc_proto_dws_message_fwd_proto_init() {
	if File_internal_adapters_grpc_proto_dws_message_fwd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDesc), len(file_internal_adapters_grpc_proto_dws_message_fwd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_grpc_proto_dws_message_fwd_proto_goTypes,
		DependencyIndexes: file_internal_adapters_grpc_proto_dws_message_fwd_proto_depIdxs,
		MessageInfos:      file_internal_adapters_grpc_proto_dws_message_fwd_proto_msgTypes,
	}.Build()
	File_internal_adapters_grpc_proto_dws_message_fwd_proto = out.File
	file_internal_adapters_grpc_proto_dws_message_fwd_proto_goTypes = nil
	file_internal_adapters_grpc_proto_dws_message_fwd_proto_depIdxs = nil
}
