// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: dws_message_fwd.proto

package dws_message_fwd

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichedEventPayloadMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	RowData       *_struct.Struct        `protobuf:"bytes,6,opt,name=row_data,json=rowData,proto3" json:"row_data,omitempty"`
	EventTime     string                 `protobuf:"bytes,7,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	EventType     string                 `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedEventPayloadMessage) Reset() {
	*x = EnrichedEventPayloadMessage{}
	mi := &file_dws_message_fwd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedEventPayloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedEventPayloadMessage) ProtoMessage() {}

func (x *EnrichedEventPayloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dws_message_fwd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedEventPayloadMessage.ProtoReflect.Descriptor instead.
func (*EnrichedEventPayloadMessage) Descriptor() ([]byte, []int) {
	return file_dws_message_fwd_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichedEventPayloadMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetRowData() *_struct.Struct {
	if x != nil {
		return x.RowData
	}
	return nil
}

func (x *EnrichedEventPayloadMessage) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *EnrichedEventPayloadMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type PushEventRequest struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Payload         *EnrichedEventPayloadMessage `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	TargetCompanyId string                       `protobuf:"bytes,2,opt,name=target_company_id,json=targetCompanyId,proto3" json:"target_company_id,omitempty"` // For routing/logging on recipient
	TargetAgentId   string                       `protobuf:"bytes,3,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	TargetChatId    string                       `protobuf:"bytes,4,opt,name=target_chat_id,json=targetChatId,proto3" json:"target_chat_id,omitempty"`
	SourcePodId     string                       `protobuf:"bytes,5,opt,name=source_pod_id,json=sourcePodId,proto3" json:"source_pod_id,omitempty"` // Added to track source for metrics
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushEventRequest) Reset() {
	*x = PushEventRequest{}
	mi := &file_dws_message_fwd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventRequest) ProtoMessage() {}

func (x *PushEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dws_message_fwd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventRequest.ProtoReflect.Descriptor instead.
func (*PushEventRequest) Descriptor() ([]byte, []int) {
	return file_dws_message_fwd_proto_rawDescGZIP(), []int{1}
}

func (x *PushEventRequest) GetPayload() *EnrichedEventPayloadMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushEventRequest) GetTargetCompanyId() string {
	if x != nil {
		return x.TargetCompanyId
	}
	return ""
}

func (x *PushEventRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *PushEventRequest) GetTargetChatId() string {
	if x != nil {
		return x.TargetChatId
	}
	return ""
}

func (x *PushEventRequest) GetSourcePodId() string {
	if x != nil {
		return x.SourcePodId
	}
	return ""
}

type PushEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional: error message or status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEventResponse) Reset() {
	*x = PushEventResponse{}
	mi := &file_dws_message_fwd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventResponse) ProtoMessage() {}

func (x *PushEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dws_message_fwd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventResponse.ProtoReflect.Descriptor instead.
func (*PushEventResponse) Descriptor() ([]byte, []int) {
	return file_dws_message_fwd_proto_rawDescGZIP(), []int{2}
}

func (x *PushEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dws_message_fwd_proto protoreflect.FileDescriptor

const file_dws_message_fwd_proto_rawDesc = "" +
	"\n" +
	"\x15dws_message_fwd.proto\x12\x0fdws_message_fwd\x1a\x1cgoogle/protobuf/struct.proto\"\x9c\x02\n" +
	"\x1bEnrichedEventPayloadMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x05 \x01(\tR\x06chatId\x122\n" +
	"\brow_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\arowData\x12\x1d\n" +
	"\n" +
	"event_time\x18\a \x01(\tR\teventTime\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\"\xf8\x01\n" +
	"\x10PushEventRequest\x12F\n" +
	"\apayload\x18\x01 \x01(\v2,.dws_message_fwd.EnrichedEventPayloadMessageR\apayload\x12*\n" +
	"\x11target_company_id\x18\x02 \x01(\tR\x0ftargetCompanyId\x12&\n" +
	"\x0ftarget_agent_id\x18\x03 \x01(\tR\rtargetAgentId\x12$\n" +
	"\x0etarget_chat_id\x18\x04 \x01(\tR\ftargetChatId\x12\"\n" +
	"\rsource_pod_id\x18\x05 \x01(\tR\vsourcePodId\"G\n" +
	"\x11PushEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2n\n" +
	"\x18MessageForwardingService\x12R\n" +
	"\tPushEvent\x12!.dws_message_fwd.PushEventRequest\x1a\".dws_message_fwd.PushEventResponseBVZTgitlab.com/timkado/api/daisi-ws-service/internal/adapters/grpc/proto;dws_message_fwdb\x06proto3"

var (
	file_dws_message_fwd_proto_rawDescOnce sync.Once
	file_dws_message_fwd_proto_rawDescData []byte
)

func file_dws_message_fwd_proto_rawDescGZIP() []byte {
	file_dws_message_fwd_proto_rawDescOnce.Do(func() {
		file_dws_message_fwd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dws_message_fwd_proto_rawDesc), len(file_dws_message_fwd_proto_rawDesc)))
	})
	return file_dws_message_fwd_proto_rawDescData
}

var file_dws_message_fwd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dws_message_fwd_proto_goTypes = []any{
	(*EnrichedEventPayloadMessage)(nil), // 0: dws_message_fwd.EnrichedEventPayloadMessage
	(*PushEventRequest)(nil),            // 1: dws_message_fwd.PushEventRequest
	(*PushEventResponse)(nil),           // 2: dws_message_fwd.PushEventResponse
	(*_struct.Struct)(nil),              // 3: google.protobuf.Struct
}
var file_dws_message_fwd_proto_depIdxs = []int32{
	3, // 0: dws_message_fwd.EnrichedEventPayloadMessage.row_data:type_name -> google.protobuf.Struct
	0, // 1: dws_message_fwd.PushEventRequest.payload:type_name -> dws_message_fwd.EnrichedEventPayloadMessage
	1, // 2: dws_message_fwd.MessageForwardingService.PushEvent:input_type -> dws_message_fwd.PushEventRequest
	2, // 3: dws_message_fwd.MessageForwardingService.PushEvent:output_type -> dws_message_fwd.PushEventResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dws_message_fwd_proto_init() }
func file_dws_message_fwd_proto_init() {
	if File_dws_message_fwd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dws_message_fwd_proto_rawDesc), len(file_dws_message_fwd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dws_message_fwd_proto_goTypes,
		DependencyIndexes: file_dws_message_fwd_proto_depIdxs,
		MessageInfos:      file_dws_message_fwd_proto_msgTypes,
	}.Build()
	File_dws_message_fwd_proto = out.File
	file_dws_message_fwd_proto_goTypes = nil
	file_dws_message_fwd_proto_depIdxs = nil
}
