account:
  name: "Daisi"

users:
  - account: "Daisi"
    email: "admin@sequinstream.com"
    password: "password"

databases:
  - name: message_service_db
    port: 5432
    ssl: false
    ipv6: false
    hostname: postgres
    password: postgres
    username: postgres
    pool_size: 10
    database: message_service_db
    use_local_tunnel: false
    slot_name: daisi_slot
    publication_name: daisi_pub

sinks:
  - name: global00_messages_sink
    status: active
    table: daisi_CompanyGLOBAL00.messages
    filters: []
    transform: none
    destination:
      port: 4222
      type: nats
      host: nats
      tls: false
    actions:
      - insert
      - update
      - delete
    batch_size: 1
    database: message_service_db
    timestamp_format: iso8601
    max_retry_count:
    load_shedding_policy: pause_on_full
    active_backfill:
    group_column_names:
      - message_id
      - message_date
  - name: global00_chats_sink
    status: active
    table: daisi_CompanyGLOBAL00.chats
    filters: []
    transform: none
    destination:
      port: 4222
      type: nats
      host: nats
      tls: false
    actions:
      - insert
      - update
      - delete
    batch_size: 1
    database: message_service_db
    timestamp_format: iso8601
    max_retry_count:
    load_shedding_policy: pause_on_full
    active_backfill:
    group_column_names:
      - chat_id
  - name: global00_agents_sink
    status: active
    table: daisi_CompanyGLOBAL00.agents
    filters: []
    transform: none
    destination:
      port: 4222
      type: nats
      host: nats
      tls: false
    actions:
      - insert
      - update
      - delete
    batch_size: 1
    database: message_service_db
    timestamp_format: iso8601
    max_retry_count:
    load_shedding_policy: pause_on_full
    active_backfill:
    group_column_names:
      - agent_id

