auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki 
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

pattern_ingester:
  enabled: true

limits_config:
  volume_enabled: true
  allow_structured_metadata: true
  # Default limits are often sufficient for local development.
  # If you encounter rate limiting or other limit-related issues,
  # you might need to adjust these. Example:
  # ingestion_rate_mb: 15
  # ingestion_burst_size_mb: 20
  # max_query_series: 10000 

ruler:
  alertmanager_url: http://localhost:9093 # Placeholder, adjust if you use Alertmanager

# For a single node setup, memberlist configuration is minimal.
memberlist:
  join_members: [] 