# Server Configuration
server:
  http_port: 8080
  grpc_port: 50051 # Corresponds to GRPC_PORT ENV

# NATS Configuration
nats:
  url: "nats://nats:4222" # Corresponds to NATS_URL ENV
  stream_name: "wa_stream"
  consumer_name: "ws_fanout"

# Redis Configuration
redis:
  address: "redis:6379" # Corresponds to REDIS_ADDR ENV
  # password: "" # If needed
  # db: 0       # If needed

# Logging Configuration
log:
  level: "info" # Corresponds to LOG_LEVEL ENV

# Authentication Configuration
auth:
  secret_token: "YOUR_32_CHAR_DAISI_WS_SERVICE_SECRET_TOKEN_HERE" # General API Key
  token_aes_key: "YOUR_64_CHAR_HEX_ENCODED_AES256_KEY_FOR_TOKENS_HERE" # For company token encryption
  token_generation_admin_key: "YOUR_32_CHAR_DEDICATED_TOKEN_GENERATION_ADMIN_KEY_HERE" # For /generate-token endpoint
  token_cache_ttl_seconds: 30
  admin_token_aes_key: "YOUR_64_CHAR_HEX_ENCODED_AES256_KEY_FOR_ADMIN_TOKENS_HERE"
  admin_token_cache_ttl_seconds: 60

# Application Specific
app:
  service_name: "daisi-ws-service"
  version: "1.0.0"
  ping_interval_seconds: 20
  shutdown_timeout_seconds: 30
  max_missed_pongs: 2
  session_ttl_seconds: 30
  route_ttl_seconds: 30
  ttl_refresh_interval_seconds: 10
  nats_max_ack_pending: 5000
  session_lock_retry_delay_ms: 250 # Delay in milliseconds for session lock retry

# Config holds all configuration for the application. 